export const QUEUE_BASE_PATTERN = {
  CORE_RES: `CORE_RES`,

  FRONTEND_QUEUE: `FRONTEND_QUEUE`,
  BACKEND_QUEUE: `BACKEND_QUEUE`,
};

export const QUEUE_PATTERN = {
  CORE_RES: `${QUEUE_BASE_PATTERN.CORE_RES}`,

  FRONTEND_QUEUE: `${QUEUE_BASE_PATTERN.FRONTEND_QUEUE}`,
  BACKEND_QUEUE: `${QUEUE_BASE_PATTERN.BACKEND_QUEUE}`,
  
};

export const QUEUE_DESTINATION = {
  CORE: `/queue/BACKEND_REQ`,
  CORE_RES: `/queue/${QUEUE_PATTERN.CORE_RES}`,

  FRONTEND_DESTINATION: `/queue/${QUEUE_PATTERN.FRONTEND_QUEUE}`,
  BACKEND_DESTINATION: `/queue/${QUEUE_PATTERN.BACKEND_QUEUE}`,
};



