export const QUEUE_BASE_PATTERN = {
	CORE_RES: `CORE_RES`,

	TEST_QUEUE: `TEST_QUEUE`,
	FRONTEND_QUEUE: `FRONTEND_QUEUE`,
	BACKEND_QUEUE: `BACKEND_QUEUE`,
	ORDER_CREATED: `ORDER_CREATED`
};

export const QUEUE_PATTERN = {
	CORE_RES: `${QUEUE_BASE_PATTERN.CORE_RES}`,

	TEST_QUEUE: `${QUEUE_BASE_PATTERN.TEST_QUEUE}`,
	FRONTEND_QUEUE: `${QUEUE_BASE_PATTERN.FRONTEND_QUEUE}`,
	BACKEND_QUEUE: `${QUEUE_BASE_PATTERN.BACKEND_QUEUE}`,
	ORDER_CREATED: `${QUEUE_BASE_PATTERN.ORDER_CREATED}`
};

export const QUEUE_DESTINATION = {
	CORE: `/queue/BACKEND_REQ`,
	CORE_RES: `/queue/${QUEUE_PATTERN.CORE_RES}`,

	TEST_DESTINATION: `/queue/${QUEUE_PATTERN.TEST_QUEUE}`,
	FRONTEND_DESTINATION: `/queue/${QUEUE_PATTERN.FRONTEND_QUEUE}`,
	BACKEND_DESTINATION: `/queue/${QUEUE_PATTERN.BACKEND_QUEUE}`,
	ORDER_CREATED_DESTINATION: `/queue/${QUEUE_PATTERN.ORDER_CREATED}`
};
