export const NO_MESSAGE_HANDLER = 'There is no matching message handler defined in the remote service.';
export const CONNECT_EVENT = 'connect';
export const CONNECTED_RMQ_MESSAGE = 'Connected to RMQ Server';
export const DISCONNECT_EVENT = 'disconnect';
export const DISCONNECTED_ACTIVEMQ_MESSAGE = 'Disconnected from ActiveMQ. Trying to reconnect.';
export const ERROR_EVENT = 'error';
export const ERROR_ACTIVEMQ_MESSAGE = 'An error occured';
export const CONNECT_FAILED_EVENT = 'connectFailed';
export const CONNECT_FAILED_ACTIVEMQ_MESSAGE = 'The connection to the server failed';
